### ISSUE TITLE
Unable to find start address

### ISSUE THREAD

**Issue by Ayak973** [EgeBalci/Cminer#1]
Hello,
When I run the Cminer application, it cannot find my exe start address.
The issue is at line 221 of Miner.h :
" | grep 'start address' >> file.dat";
Objdump displays the informations accordingly to the system language. When it is not english, this line didn't work (I had to modify this line in " | grep 'adresse de départ' >> file.dat").
Are you planning to release a multi lingual tool?

**Comment by EgeBalci** [comment]
Hello,
Thanks for pointing this out i was thinking about rewriting the tool's binary parsing mechanism without the help of objdump. It will probably going to solve this issue.  Until then people who are having the same problem can use your solution :) Thanks again.

**Comment by giper45** [comment]
Hi , something like this?  
| awk '{ if (NR==6) print $0 }'  
Not sure if objdump NR line of start address is always equal to 6. 
Best regards

**Comment by EgeBalci** [comment]
I'll rewrite this without using objdump. :+1:
